baseurl = "https://eclipse.dev/4diac"
DefaultContentLanguage = "en"
title = "Eclipse 4diac"
theme = "hugo-solstice-theme"
metaDataFormat = "yaml"
disableKinds = []
enableRobotsTXT = true
pluralizeListTitles = false

timeout = "120s"

[Params]
#  google_tag_manager = "GTM-5WLCZXC"
  description = "The Eclipse Foundation provides our global community of individuals and organizations with a mature, scalable, and business-friendly environment for open source software collaboration and innovation."
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["eclipse", "project", "plug-ins", "plugins", "java", "ide", "swt", "refactoring", "free java ide", "tools", "platform", "open source", "development environment", "development", "ide"]
  news_count = 3
  gcse = "011805775785170369411:p3ec0igo0qq"
  header_wrapper_class = "header-wrapper header-default-bg-img featured-jumbotron-bottom-shape"
  call_for_action_text = "Download"
  call_for_action_url = "/4diac/download/"
  call_for_action_icon = "fa-download"
  logo = "/4diac/img/4diac_Logo_2024.svg"
  logo_url = "/4diac/"
  logo_width = "55%"
  layout_style = "astro"
  style_overrides="css/4diac_adjustments.css"
  sidebar_layout = "default"
# featured_content_publish_target = "eclipse_org"
# js = ""
  favicon = "/4diac/img/4diac_favicon.svg"
# share_img = ""
# header_left_classes = ""
# main_menu_wrapper_classes = ""
# projects_working_group = ""
  show_featured_footer = false
  hide_footer_newsletter = true
  twitter_url = "https://x.com/4diac"
  youtube_url = "https://www.youtube.com/@4diac177" 
  linkedin_url = "https://www.linkedin.com/groups/6949091/"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[Author]
  name = "Eclipse 4diac Team"
  website = "https://eclipse.dev/4diac/"
  email = "4diac-dev@eclipse.org"
  facebook = "eclipse.org"
  twitter = "ECDTools"
  youtube = "EclipseFdn"
  linkedin = "company/eclipse-foundation/"
  
[security.exec]
  allow = ["^asciidoctor$"]

[module]
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "submodules/4diac-documentation/src"
    target = "content/doc"

[markup]
  [markup.asciidocExt]
    workingFolderCurrent = true  # Include paths relative to the file
  [markup.asciidocExt.attributes]
      skip-front-matter = "true"  # Tell Asciidoctor to ignore Hugo's front matter

[permalinks]
  news = "/:sections/:year/:slug/"
  # news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
  name = "Eclipse 4diac"
  weight = 1
  identifier = "fordiac"
  [menu.main.params]
    description = """
      Eclipse 4diac™ provides an open source infrastructure
      for distributed industrial process measurement and control systems
      based on the IEC 61499 standard.
    """

[[menu.main]]
  name = "Explore Eclipse 4diac"
  weight = 1
  identifier = "fordiac-projects"
  parent = "fordiac"

[[menu.main]]
  name = "4diac IDE"
  url = "/4diac_IDE/"
  weight = 1
  parent = "fordiac-projects"

[[menu.main]]
  name = "4diac FORTE"
  url = "/4diac_FORTE/"
  weight = 2
  parent = "fordiac-projects"

[[menu.main]]
  name = "4diac FBE"
  url = "/4diac_FBE/"
  weight = 3
  parent = "fordiac-projects"

[[menu.main]]
  name = "4diac LIB"
  url = "/4diac_LIB/"
  weight = 5
  parent = "fordiac-projects"

[[menu.main]]
  name = "4diac SYS"
  url = "/4diac_SYS/"
  weight = 6
  parent = "fordiac-projects"

[[menu.main]]
  name = "Our Community"
  weight = 2
  identifier = "fordiac-community"
  parent = "fordiac"

[[menu.main]]
  name = "Committers"
  url = "/team/"
  weight = 1
  parent = "fordiac-community"

[[menu.main]]
  name = "Mailing List"
  url = "https://dev.eclipse.org/mailman/listinfo/4diac-dev"
  weight = 2
  parent = "fordiac-community"

[[menu.main]]
  name = "Matrix Chat"
  url = "https://chat.eclipse.org/#/room/#eclipse-4diac:matrix.eclipse.org"
  weight = 3
  parent = "fordiac-community"

[[menu.main]]
  name = "Q&A / Discussions"
  url = "/support/#discussions"
  weight = 4
  parent = "fordiac-community"

[[menu.main]]
  name = "Report an Issue"
  url = "https://github.com/eclipse-4diac"
  weight = 5
  parent = "fordiac-community"


[[menu.main]]
  name = "News"
  weight = 2
  identifier = "news"
  url = "/news/"

[[menu.main]]
  name = "Events"
  weight = 3
  identifier = "events"
  [menu.main.params]
    description = """
    Eclipse 4diac™ has been founded to support research activities and industrial adoption of distributed automation systems. 
    Over time 4diac grew with new versions, improvements and new features for the modeling of distributed automation systems. 
    Moreover, a special focus was the performance improvement of the runtime system. Even more important, 4diac as an 
    IEC 61499-compliant distributed control environment for industrial and research applications has proven 
    to be a stable basis for further research towards the next generation of distributed automation and control systems based 
    on open standards. To get in contact with its users and share results and future plans 4diac participates at different events, 
    which are collected here:
    """

[[menu.main]]
  name = "Winter Schools"
  weight = 1
  identifier = "events-winterschools"
  parent = "events"
  
[[menu.main]]
  name = "1st 4days of Eclipse 4diac Winter School, 2025" 
  url = "/events/4diacWinterSchool/"
  weight = 1
  parent = "events-winterschools"
  

[[menu.main]]
  name = "Community Events"
  weight = 2
  identifier = "events-community"
  parent = "events"

[[menu.main]]
  name = "Eclipse 4diac Virtual Community Meetings"
  url = "/events/virt-community/"
  weight = 1
  parent = "events-community"

[[menu.main]]
  name = "4days of 4diac, 2019"
  url = "/events/workshops/2019_4days_of_4diac/"
  weight = 2
  parent = "events-community"

[[menu.main]]
  name = "Eclipse Insight: Cross Domain Engineering, 2019"
  url = "/events/workshops/2019_eclipse_insight/"
  weight = 2
  parent = "events-community"

[[menu.main]]
  name = "ETFA Workshops"
  weight = 3
  identifier = "events-etfa_workshops"
  parent = "events"

[[menu.main]]
  name = "7th 4diac Users' Workshop @ ETFA 2016"
  url = "/events/etfa/etfa2016/"
  weight = 1
  parent = "events-etfa_workshops"

[[menu.main]]
  name = "6th 4diac Users' Workshop @ ETFA 2015"
  url = "/events/etfa/etfa2015/"
  weight = 2
  parent = "events-etfa_workshops"

[[menu.main]]
  name = "5th 4diac Users' Workshop @ ETFA 2014"
  url = "/events/etfa/etfa2014/"
  weight = 3
  parent = "events-etfa_workshops"

[[menu.main]]
  name = "4th 4diac Users' Workshop @ ETFA 2013"
  url = "/events/etfa/etfa2013/"
  weight = 4
  parent = "events-etfa_workshops"

[[menu.main]]
  name = "3rd 4diac Users' Workshop @ ETFA 2012"
  url = "/events/etfa/etfa2012/"
  weight = 5
  parent = "events-etfa_workshops"

[[menu.main]]
  name = "2nd 4diac Users' Workshop @ ETFA 2011"
  url = "/events/etfa/etfa2011/"
  weight = 6
  parent = "events-etfa_workshops"

[[menu.main]]
  name = "1st 4diac Users' Workshop @ ETFA 2010"
  url = "/events/etfa/etfa2010/"
  weight = 7
  parent = "events-etfa_workshops"


  [[menu.main]]
  name = "Support"
  weight = 4
  identifier = "support"
  url = "/support/"
  [menu.main.params]
    description = """
    support 4diac.
    """

  [[menu.main]]
  name = "Contribute"
  weight = 5
  identifier = "contribute"
  url = "/contribute/"
  [menu.main.params]
    description = """
    contribute to 4diac.
    """

[[menu.main]]
  name = "Documentation"
  weight = 6
  identifier = "documentation"
  [menu.main.params]
    description = """
    Documentation for Eclipse 4diac. 
    """

[[menu.main]]
  name = "Getting Started"
  weight = 1
  identifier = "doc-getting_started"
  parent = "documentation"

[[menu.main]]
  name = "Documentation Start"
  url = "/doc/"
  weight = 1
  parent = "doc-getting_started"

[[menu.main]]
  name = "Learn about IEC 61499"
  url = "/doc/intro/iec61499.html"
  weight = 2
  parent = "doc-getting_started"

[[menu.main]]
  name = "Understand the Eclipse 4diac Framework"
  url = "/doc/intro/4diacFramework.html"
  weight = 3
  parent = "doc-getting_started"

[[menu.main]]
  name = "Using Eclipse 4diac"
  weight = 2
  identifier = "doc-using"
  parent = "documentation"

[[menu.main]]
  name = "Step by Step Tutorials"
  url = "/doc/tutorials/overview.html"
  weight = 1
  parent = "doc-using"

[[menu.main]]
  name = "Install Eclipse 4diac"
  url = "/doc/installation/installation.html"
  weight = 2
  parent = "doc-using"

[[menu.main]]
  name = "4diac IDE Examples"
  url = "/doc/examples/examples.html"
  weight = 3
  parent = "doc-using"

[[menu.main]]
  name = "Frequently Asked Questions"
  url = "/doc/faq.html"
  weight = 4
  parent = "doc-using"
  
[[menu.main]]
  name = "Details"
  weight = 3
  identifier = "doc-details"
  parent = "documentation" 

[[menu.main]]
  name = "IO Configuration for the Different Platforms"
  url = "/doc/io_config/io_config.html"
  weight = 1
  parent = "doc-details"

[[menu.main]]
  name = "Communication Protocols"
  url = "/doc/communication/communication.html"
  weight = 2
  parent = "doc-details"

[[menu.main]]
  name = "Development of 4diac FORTE and 4diac IDE"
  url = "/doc/development/development.html"
  weight = 2
  parent = "doc-details"



[[sidebar]]
    name = "News"
    url = "/news/"
    weight = 2
    pre = "<i class=\"sidebar-menu-icon\" data-feather=\"github\"></i>"
    identifier = "news_sidebar"

[[sidebar]]
    name = "2024"
    url = "/news/2024/"
    weight = 1
    parent = "news_sidebar"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
    identifier = "2024"

[[sidebar]]
    name = "2023"
    url = "/news/2023/"
    weight = 2
    parent = "news_sidebar"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
    identifier = "2023"

[[sidebar]]
    name = "News of 2024"
    url = "/third-parent/test-children/test-children-children/"
    weight = 1
    parent = "news_sidebar-2024"

[[sidebar]]
    name = "News of 2023"
    url = "/third-parent/test-children/test-children-children/"
    weight = 2
    parent = "news_sidebar-2023"
    
    
# Side bar for download page
[[menu.sidebar]]
  identifier = "sidebar-downloads"
  name = "Early Access"
  weight = 1  

[[menu.sidebar]]
  parent = "sidebar-downloads"
  identifier = "sidebar-downloads-IDE"
  name = "4diac IDE 3.0"
  weight = 1  
  
[[menu.sidebar]]
  parent = "sidebar-downloads-IDE"
  name = "Linux 64-bit"
  url = "https://www.eclipse.org/downloads/download.php?file=/4diac/updates/rc/4diac-ide_3.0.0-linux.gtk.x86_64.tar.gz"
  weight = 1     

[[menu.sidebar]]
  parent = "sidebar-downloads-IDE"
  name = "Windows 64-bit"
  url = "https://www.eclipse.org/downloads/download.php?file=/4diac/updates/rc/4diac-ide_3.0.0-win32.win32.x86_64.zip"
  weight = 2     

[[menu.sidebar]]
  parent = "sidebar-downloads-IDE"
  name = "Mac OS X x86"
  url = "https://www.eclipse.org/downloads/download.php?file=/4diac/updates/rc/4diac-ide_3.0.0-macosx.cocoa.x86_64.dmg"
  weight = 3

[[menu.sidebar]]
  parent = "sidebar-downloads-IDE"
  name = "Mac OS X aarch64"
  url = "https://www.eclipse.org/downloads/download.php?file=/4diac/updates/rc/4diac-ide_3.0.0-macosx.cocoa.aarch64.dmg"
  weight = 4
  
[[menu.sidebar]]
  parent = "sidebar-downloads"
  identifier = "sidebar-downloads-FORTE"
  name = "4diac FORTE 3.0"
  weight = 2  
  
[[menu.sidebar]]
  parent = "sidebar-downloads-FORTE"
  name = "4diac FORTE source"
  url = "https://github.com/eclipse-4diac/4diac-forte/archive/refs/heads/freeze.zip"
  weight = 1       
    
